### ISSUE TITLE
Support for update-rows operation?

### ISSUE THREAD

**Issue by tcash21** [cole-johanson/smartsheetr#13]
Hello, I need to set a value for a picklist column, but the API doesn't seem to allow this via `ss_add_rows`.

```
Error in `ss_api()`:
! SmartSheet API request failed [400]
Value is not supported for this column type. Use objectValue instead.
```

Are you planning on adding an API call for [updating rows](https://smartsheet.redoc.ly/tag/rows#operation/update-rows)? I may be able to help contribute if not.  Thank you.

**Comment by cole-johanson** [comment]
@tcash21 yes, there is a PR for updating rows. See https://github.com/cole-johanson/smartsheetr/pull/9. I plan on publishing later this month, but in the mean time, feel free to install the develop branch.
